### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by debajyotidasgupta**
This I feel would describe the project better

### CODE REVIEW

**Comment by rahulkumaran** [comment]
Could you put up a screenshot of how exactly it looks? @debajyotidasgupta

**Comment by debajyotidasgupta** [comment]
screenshot from 2018-12-06 15-19-29

**Comment by rahulkumaran** [comment]
Thanks for the PR. Merging it now

Also, one thing. From next time, please reference the issue number that you've worked on through this PR

**Comment by debajyotidasgupta** [comment]
yeah sure

**Pull request merged**
