### PR TITLE
capture returned value

### PR DESCRIPTION
**Pull request by ayushk203**

### CODE REVIEW

**Comment by rahulkumaran** [comment]
Can you put up screenshots of a test case where you call a function and return its value to a variable

**Comment by ayushk203** [comment]
i'll put screenshots by today's night and if you think i have done anything wrong please tell,this is my first time with open source so i can do a lot of mistakes

**Comment by rahulkumaran** [comment]
Sure. Also, make sure to add comments to every line. Else, I won't be able to merge it. Want it to be a project that anyone and everyone can understand. Comments will be extremely helpful.

**Comment by ayushk203** [comment]
I'll take care of it from next time

ᐧ

**Comment by rahulkumaran** [comment]
Either way, @ayushk203 please add comments to this PR. Probably one commit for adding comments at all lines that you have added to the code.

**Comment by ayushk203** [comment]
i'm currently having some problems with my pc whatever is the problem i'll
try to solve it by tomorrow

ᐧ

**Comment by rahulkumaran** [comment]
Hi @ayushk203 , this is taking too long. I'll be passing this over. But don't worry, you will be credited for whatever you've done! 

Cheers!

**Pull request closed without merging**
